### ISSUE TITLE
Interfaz

### ISSUE THREAD

**Issue by edelap00** [CIFP-Jose-luis-Garci/TheSingularity#10]
- [x] Mapa de Navegación
- [ ] Menús
- [ ] Hud

**Comment by agusizbus** [comment]
**MAPA DE NAVEGACIÓN INTERFAZ**
[Mapa flujo de navegación Singularity.pdf](https://github.com/CIFP-Jose-luis-Garci/TheSingularity/files/7519218/Mapa.flujo.de.navegacion.Singularity.pdf)

**Comment by agusizbus** [comment]
HUD
![HUD](https://user-images.githubusercontent.com/77756482/141518644-d4d1a8fd-1078-437c-9f12-e9a5bf2afd0f.png)

**Comment by agusizbus** [comment]
Ejemplos pantallas interfaz

![Ejemplo menú 1](https://user-images.githubusercontent.com/77756482/141530510-bb3da70d-7c76-43e8-939a-0a0dfeea054d.png)
![Iniciar](https://user-images.githubusercontent.com/77756482/141530513-58677aae-50f9-4e02-9775-c56523ef3db0.png)
![Menú 2](https://user-images.githubusercontent.com/77756482/141530515-8f23095e-ac42-44ea-9c36-06d3d0077861.png)
![Menú pause](https://user-images.githubusercontent.com/77756482/141530517-2ddf91fa-6ae8-4f33-a12c-688f47cc9857.png)
![Menú principal](https://user-images.githubusercontent.com/77756482/141530518-352d425e-7282-46c9-9c9e-d8d6598fd57b.png)
