### ISSUE TITLE
Dinámicas y mecánicas

### ISSUE THREAD

**Issue by edelap00** [CIFP-Jose-luis-Garci/TheSingularity#11]
Concretar

**Comment by agusizbus** [comment]
El juego se desarrolla entorno a una dinámica de progreso en todos los aspectos donde aunque pierdas sigues progresando y con ganas de seguir jugando. Pero la frustración será una parte a fomentar, jugando continuamente con las ganas de que el jugador continúe.

Para conseguir la dinámica de progreso podemos dividirla en dos objetivos:
- Progreso en jugabilidad
El juego va a girar entorno a una mecánica de pelea y subida de nivel. Al principio la curva de dificultad será alta ya que tendremos que acostumbrarnos a los patrones de ataque de los enemigos, que irán haciéndose progresivamente mucho más fuertes.
Para crear esa sensación de progreso vamos a generar una dinámica de recompensas que nos permitan aumentar el nivel de nuestra fuerza, defensa y velocidad que nos permitirán cada vez sentirnos más fuertes al volver a intentar pelear contra los enemigos.
Estas recompensas serán experiencia (La moneda del juego) y runas (objetos equipables que nos aumentan estadísticas) que soltarán los enemigos cuando los derrotamos. Los bosses nos darán a parte, objetos más grandes. Esto conlleva una mecánica de gestión de inventario.
Solo se podrá aumentar de nivel al morir, por lo tanto, perder nos podrá ayudar y la frustración no será tan grande y nos motivará a volver a intentarlo con los nuevos objetos conseguidos y un nivel mayor.
La muerte es una de las mecánicas más importantes del juego también.


- Progreso en la historia
La dinámica de progreso en la historia será por medio de la mecánica de muerte. Cada vez que mueras, tendrás la opción de conocer un poco más de la historia de los dioses, su mitología y su relación entre ellos. Ya que podremos hablar con Vaer, que es la que nos va a contar todo esto a parte de subir nuestro nivel.
Pero la historia principal se contará en 6 cinemáticas principales, donde tendrás un hilo básico con el que entender la historia. Cada cinemática será al inicio y al final del salto temporal.
Sin embargo podremos conocer una parte oculta de la historia usando una mecánica de exploración, que nos permitirá, buscando por el mapa e interactuando con objetos, conocer una parte oculta de la historia que cambiará nuestra perepción y aumentará la rejugabilidad del título. Que será fomentada también con una mecánica de decisiones donde podremos tener dos finales diferentes antes de la batalla final, valorando todo lo descubierto en el juego.

-Dinámica de competición y comunidad
Uno de los modos de juego será para acabarlo sin recibir un solo golpe, esto podrá generar contenido en la comunidad no-hitter que tanto está creciendo en twitch. Además tendremos un ranking de los que lo hayan completado de forma más rápida y con menos nivel.

**Comment by vcalzadaga** [comment]
Muy bien explicado
