### ISSUE TITLE
Movimientos y físicas

### ISSUE THREAD

**Issue by edelap00** [CIFP-Jose-luis-Garci/TheSingularity#12]
- [ ] Controles
- [ ] Interacción entre elementos

**Comment by ByAlvaroFB** [comment]
Movimiento estándar controlado por el joystick o wasd. 

El movimiento se caracteriza por ser bastante rápido para darle una sensación de velocidad al jugador en los enfrentamientos, para lograrlo una característica principal del movimiento de este sería un dash el cual nos servirá para desplazarnos más rápido o esquivar ataques enemigos ( Espacio / A Xbox)

Nuestro personaje puede contar con dos tipos de arma:

Armas ligeras: nos permiten atacar rápidamente a nuestros enemigos con un daño considerable (Click izquierdo / X Xbox)
Armas pesadas; nos permiten realizar un ataque pesado más lento de ejecutar pero con un daño mucho mayor (Click derecho / Y Xbox)

Nuestro personaje también utilizará magia en forma de proyectil para lanzárselo a los enemigos, a la hora de realizarlo se podra mover mas lentamente y si le atacan se cancelara el lanzamiento.

Nuestro personaje puede recibir dos tipos de golpe:

Ligero: proporcionado por enemigos ligeros y arqueros, al recibir daño de estos el personaje realizara una animación corta de daño para no pausar demasiado el combate
Potente: proporcionado por los tanques, este ataque te produce un daño considerable y empuja al jugador bastante lejos aturdiendolo por unos instantes.

A la hora de curarnos el jugador hara una pequeña animacion que requerira de que este este quieto y se cancelara si este recibe daño

Movimiento de los enemigos

Ligero: este enemigo ira directamente a por el jugador, se movera y atacara de una forma rápida, sus ataques podrán ser cancelados si el jugador ataca antes que este.
Pesado / Tanque: este enemigo irá directamente a por el jugador, se moverá más despacio y atacara mas lento pero sus ataques serán más potentes y tendrá mucho aguante, este no cancela su ataque si la atacas antes
Arquero: este enemigo procurará mantener la distancia respecto al jugador para que este no lo alcance y poder lanzar sus proyectiles, se podrán cancelar sus lanzamientos al atacarle previamente.
