### ISSUE TITLE
Estilo Visual

### ISSUE THREAD

**Issue by AlexLabrador** [CIFP-Jose-luis-Garci/TheSingularity#13]
- [x] Concept art
- [x] Diseño de personajes
- [x] Objetos, armas power up ,coleccionables...
- [x] Otros

**Comment by agusizbus** [comment]
**Estética**
En general el juego tendrá una estética de Cel Shading anime (Veáse Zelda Breath of the wild o la saga de juegos Naruto Ultimate Ninja Storm)

**Línea temporal**
Al desarrollarse el juego en diferentes partes del tiempo vamos a concretar puntos clave para el diseño de los concepts:

- **Etapa** Nórdica
Lo más destacable son los campos verdes manchados por la nieve del invierno, auroras boreales a plena mañana y casas pequeñas de madera. Carruajes por medio de la calle y estética medieval.
Los personajes y enemigos estarán en estado base. Eyra portará armas normales y un vestuario medieval.
- **Etapa Cyberpunk**
El punto central es la cantidad de luces de neon adornando todo. Habrá una lluvia constante y será de noche, iluminado todo por farolas y neones. 
Coches futuristas en medio de la carretera y edificios modernos llenos de neones.
Los personajes y enemigos tendrán partes brillantes en ciertos puntos. Eyra usará armas como las anteriores pero con adornos de neon.
- **Etapa Post-Apocalipsis**
Para demostrar el paso del tiempo, la naturaleza habrá retomado la ciudad y todo estará lleno de plantas. El cielo estará gris debido a la polución y solo algunos neones seguirán parpadeando a duras penas. Todo lo que antes era metálico ahora está oxidado.
Los enemigos tendrán partes no funcionales y con cables sueltos, además de chispas saliendo continuamente. Las armas de Eyra, igualmente tendrán cables sueltos y muchos metales sueltos las adornarán.

**Comment by agusizbus** [comment]
Concept art del personaje principal

![Boeto_Eyra_Colorbaja](https://user-images.githubusercontent.com/77756482/141206965-f97af4ff-3580-431d-90d3-c5f53a632926.jpg)

**Comment by agusizbus** [comment]
**Concept art Batalla contra la hidra**
![Escena2 copia 2](https://user-images.githubusercontent.com/77756482/141207363-45519268-9132-4807-9eca-227a01d8c02b.jpg)
![Escena3 copia 2](https://user-images.githubusercontent.com/77756482/141207364-c00f74f2-b679-49ed-a874-c2731b5ee060.jpg)
![Esscena 7 copia](https://user-images.githubusercontent.com/77756482/141207365-968c5e1c-aef8-4312-ae5e-3742748c9576.jpg)
![Escena 6 copia](https://user-images.githubusercontent.com/77756482/141207366-d6979d78-60f5-41de-947b-316bcdeb08eb.jpg)
![Escena 8 1 copia](https://user-images.githubusercontent.com/77756482/141207367-07d17b20-aaef-4a93-8ba1-bdd06a7aa741.jpg)
![Escena 9 copia 5](https://user-images.githubusercontent.com/77756482/141207370-6a7d87ec-f16b-434a-a7e1-ebc5bdda10ce.jpg)

**Comment by agusizbus** [comment]
**Primer boceto Diosa Vaer**
![Primer Boceto](https://user-images.githubusercontent.com/77756482/141207621-e8c7e306-888b-4574-9025-e431660d6c3c.png)

**Comment by agusizbus** [comment]
**Enlace a Referencias Visuales a estudiar**
https://www.pinterest.es/agusizbus99/singularity/

**Comment by agusizbus** [comment]
Concept art Vaer

![Art concept](https://user-images.githubusercontent.com/77756482/141377802-3a4b7e71-9950-48e5-8410-6c8e40004363.jpg)

**Comment by agusizbus** [comment]
Vaer Art Concept

![Vaer Art concept](https://user-images.githubusercontent.com/77756482/141381554-04ab3d81-de54-4e11-a996-d17d24897b87.jpg)

**Comment by agusizbus** [comment]
Ghoul Art concept
![Ghoul_Concept](https://user-images.githubusercontent.com/77756482/141381585-50cf6ec2-0360-48dc-bec5-5e1f0707baa4.jpg)

**Comment by agusizbus** [comment]
Golem Concept Art

![Golem](https://user-images.githubusercontent.com/77756482/141387935-e1bc4eaf-8f18-4498-b4b1-66b9cea1d2d8.jpg)

**Comment by agusizbus** [comment]
Ghast Concept art
![Ghast concept](https://user-images.githubusercontent.com/77756482/141387969-abb5de96-4247-47ab-a11b-159351992f83.jpg)

**Comment by agusizbus** [comment]
Modelos y conceptos armas

![Espada](https://user-images.githubusercontent.com/77756482/141388359-eaf66b3a-b73e-44c8-a2be-c11e36449361.png)
![Hacha 2](https://user-images.githubusercontent.com/77756482/141388362-606bfcd4-e516-4cfd-9f1d-604980a5c4d0.png)
![Hacha 12](https://user-images.githubusercontent.com/77756482/141388363-8d5e76cb-3d98-4a7a-9bef-c2b4845e5367.png)
![Lanza](https://user-images.githubusercontent.com/77756482/141388366-bae4fb7e-9542-45c5-bd66-06aa4be6c9c3.png)
