### ISSUE TITLE
Diseño de niveles

### ISSUE THREAD

**Issue by edelap00** [CIFP-Jose-luis-Garci/TheSingularity#14]
- [x] Objetivo del jugador
- [x] Flujo de juego
- [x] Niveles de Juego
- [x] Dificultad
- [x] Tutorial

**Comment by OscarGSanchez** [comment]
Flujo de trabajo (Primera parte)

A lo largo de esta sección se detallará el transcurso de una partida de Singularity. Se comentarán los
pasos que ha de seguir el Jugador desde que empieza el juego hasta completar un nivel. Iremos desarrollando el funcionamiento del juego.

El jugador inicia Singularity y lo primero que se le presenta es una portada con el titulo donde tiene que pulsar el botón start para llegar al menú principal. Singularity soporta varias partidas guardadas, pero al ser la primera, tendrá que empezar una nueva partida y a continuación, elegir la dificultad. También tendrá una pestaña de configuración donde podrá modificar ajustes de audio, video, asignación de teclas, o controles. 

Los niveles se organizan de forma secuencial, eso quiere decir que cuando se completa uno, se desbloqueará el siguiente. Al principio de cada nivel, tendrá una pequeña plaza donde podrá organizar su inventario, seleccionando que objetos se quiere equipar antes de empezar el nivel, y subirse las estadisticas si es lo que quiere.

El jugador comenzará en la casa de la protagonista, se encontrará en el exterior, y tendrá que luchar contra una serie de monstruos que le derrotaran obligatoriamente. A continuación una diosa le revivirá y le dará una segunda oportunidad, pero con un brazalete que le otorgará armas para ahora si poder defenderse y ganar. Aquí aprenderá la mecánica más importante del juego, que es la posibilidad de revivir con la experiencia y los objetos ganados, pero empezando el nivel de nuevo. De vuelta a la plaza, podrá volver a organizar los objetos que llevará equipados, pero sabiendo a que tipo de enemigos se tendrá que enfrentar y subirse las estadísticas.

**Comment by OscarGSanchez** [comment]
Como se ha dicho antes, el jugador puede morir, pero tiene una cantidad ilimitada de intentos ya que el nivel se reiniciará y volverá a empezar.

Cada vez que el jugador se pase un nivel, avanzará al siguiente y podrá volver a la plaza principal y cambiar su equipo si es necesario.

**Comment by OscarGSanchez** [comment]
Niveles de juego 

Cada nivel de Singularity, es una zona de la ciudad natal del Eyra, que ira cambiando y adaptándose a medida que vayamos avanzando en el juego. Nos encontramos con escenarios en exterior, pero con callejuelas y plazas, dando la sensación de ir avanzando por mazmorras diferentes. Existirán habitaciones secretas que el jugador tendrá que descubrir por si mismo mediante pistas o explorando el mapa exhaustivamente para no saltarse nada, ya que estas habitaciones nos revelaran secretos importantes en la historia y nos otorgarán objetos especiales con los que poder equiparnos.

Los enemigos se encontrarán preparados para luchar en las zonas diseñadas para ello, y en estas zonas también existirán objetos destruibles como cajas o barriles. Habremos vencido cuando hayamos derrotado a todos los monstruos.

**Comment by OscarGSanchez** [comment]
La dificultad de Singularity está determinada por la cantidad de enemigos que hay en cada nivel y de la cantidad de daño que aplican a nuestro personaje. Esto varia dependiendo de nuestra resistencia, el tipo de enemigo y su nivel. La intensidad y la dificultad irán creciendo a medida que avancemos en la historia, tal y como se explica en la siguiente grafica.

![Diseño sin título](https://user-images.githubusercontent.com/77571023/141213705-04045885-4ac5-44e4-9745-72afc80ac598.png)

**Comment by OscarGSanchez** [comment]
**Objetivo del jugador**

El objetivo principal del jugador dentro de Singularity será avanzar en los niveles lo máximo que pueda hasta que llegue a un punto donde no tenga el daño, la defensa o los objetos necesarios que le ayuden a superar un punto determinado de la historia. Esto obliga al jugador a aprender de sus errores, cambiando de accesorios siempre que se necesite dependiendo de los niveles y subirse de nivel las estadísticas en el orden que él mismo decida.

Una vez que el jugador tenga la posibilidad de seguir explorando el mapa, deberá estar atento a sus alrededores para descubrir las zonas secretas que le ampliarán la historia para escoger el mejor final. En algunos casos necesitará tener un determinado nivel para poder abrir zonas secretas, obligando a jugador a reiniciar el nivel obligatoriamente si quiere explorarlas.

**Comment by agusizbus** [comment]
Mapa de flujo de jue
[Flujo de Juego Singularity.pdf](https://github.com/CIFP-Jose-luis-Garci/TheSingularity/files/7519161/Flujo.de.Juego.Singularity.pdf)
go

**Comment by OscarGSanchez** [comment]
**Tutorial**

El jugador comenzará el primer nivel sin el brazalete, pero se le explicará los controles básicos como moverse, abrir el menú, inventario y atacar con el arma básica. Una vez el jugador sea derrotado, se le explicará el funcionamiento del brazalete, en que menú equipar los accesorios y con que botones cambiar de armas y pociones. 

Se le mostrarán al jugador todos los tipos de enemigos por rondas, donde podrá ver las características principales de cada enemigo:

- Enemigo estándar: Este enemigo atacará y se moverá rápidamente y tendrá una barra de vida estándar. Sus ataques serán normales, no moverán al jugador cuando reciba el golpe. 
- 
- Enemigo pesado: Los enemigos pesados dispondrán de una armadura que tendremos que romper antes de poder derrotarlo. Dispondrá de un golpe fuerte que desplazara al jugador lejos de él. Son lentos, pero fuertes.
- 
- Enemigos a distancia: Disparará al jugador proyectiles desde lejos, dispondrá de menor vida y serán mas fácil derrotarlos, pero se convertirá en una molestia a la larga si no se les derrota primero.

Una vez terminada la lucha y vistas las cinemáticas, aprenderemos como movernos por la plaza inicial. El jugador aprenderá como, donde organizar y equiparse los objetos del inventario, como subir de nivel sus estadísticas básicas y que necesita para ello.

El jugador tendrá la opción de activar o desactivar la barra de vida de los enemigos.

**Comment by agusizbus** [comment]
**FLUJO DE JUEGO*
[Flujo de Juego Singularity.pdf](https://github.com/CIFP-Jose-luis-Garci/TheSingularity/files/7519203/Flujo.de.Juego.Singularity.pdf)
*
