### ISSUE TITLE
Música y efectos

### ISSUE THREAD

**Issue by AlexLabrador** [CIFP-Jose-luis-Garci/TheSingularity#15]
Estilo sonoro y efectos representativos del juego

**Comment by agusizbus** [comment]
**Menú principal**
El juego tendrá música tranquila y de ambiente en el menú principal con toques fantásticos. (Ref. Zelda Breath of the Wild)

**Gameplay**
Durante el gameplay solo habrá sonido ambiental (pisadas, lluvia, ríos, pájaros, gotas) hasta el comienzo de las batallas que será de acción pero prácticamente todo percusión. 

**Batalla**
En la pelea contra los bosses la música pasará a ser característica y diferente para cada boss con un tono más similar a una orquesta. (Refs: Final Fantasy Acción, Dark souls Bosses.)

**Interfaz**
Habrá un sonido para cada vez que cambias de opción en el menú, otro para aceptar y otro para cancelar/volver atrás.

**Enemigos**
Cada enemigo tendrá un sonido de ataque, otro para cuando muere y otro cuando te ve por primera vez. Serán diferentes entre tipo de enemigo. También habrá un sonido de impacto cuando te golpeen con proyectiles o diferentes tipos de armas.

El sonido de los enemigos comunes será diferente 
Normal : Gruñido Lobo
Golem : Gruñido Grave y sonido de rocas cayendo
Espíritu : Susurro fantasmagórico

Cada boss tendrá un sonido por cada tipo de ataque que realice.

**Armas**

Cada arma que usemos tendrá tres tipos de sonido; uno para el ataque rápido, otro para el ataque pesado y otro para la habilidad especial.

Habrá una música diferente para cuando mueres en batalla, como la del menú principal pero con un tono menor y más lento.

**Comment by OscarGSanchez** [comment]
**Gameplay**
Durante el gameplay habrá sonido ambiental (pisadas, lluvia, ríos, pájaros, gotas) y música de fondo hasta el comienzo de las batallas que será de acción pero prácticamente todo percusión.

**Comment by vcalzadaga** [comment]
Necesito que se incluya una muestra representativa de sonidos (durante el menú, durante el gameplay, algún efecto...). Aunque no sean los sonidos que finalmente se incluyan en el juego, por lo menos que muestren la estética sonora que buscáis implementar

**Comment by agusizbus** [comment]
**Inspiraciones sonidos:**
Menú principal: https://www.youtube.com/watch?v=cPWBG6_jn4Y&ab_channel=Peri%C3%B3dicodeHyrule
Batalla: https://www.youtube.com/watch?v=VQOloqblz1k&list=PLC02pFkh-IDH4QGv53h_tEPWOw17G2Nrx&index=12&ab_channel=MekkahDee
Batalla boss: https://www.youtube.com/watch?v=kVkKrwSwTKQ&list=PLC02pFkh-IDH4QGv53h_tEPWOw17G2Nrx&index=7&ab_channel=MekkahDee
Interfaz: https://www.youtube.com/watch?v=D0IfDOqZKZU&ab_channel=BellaKidd
Golem: https://youtube.com/clip/UgkxdXqF2awRBn-2vCLAJc0ZxiJPF_UV6b5-
Ghast: https://www.youtube.com/watch?v=Y7xsCsqGvAc&ab_channel=MotionArray
Ghoul: https://www.youtube.com/watch?v=jzDMlxV7Y9k&ab_channel=Hakoom
Bosses: https://www.youtube.com/watch?v=TiJKccilGso&ab_channel=AnisZeus
