### ISSUE TITLE
Alcance

### ISSUE THREAD

**Issue by AlexLabrador** [CIFP-Jose-luis-Garci/TheSingularity#17]
Que tenemos pensado desarrollar de aquí a marzo

**Comment by edelap00** [comment]
De aquí a final de curso se va a desarrollar una demo jugable del nivel que se encuentra en el periodo cyberpunk de la línea temporal , con la muestra de la batalla con el boss final (Hidra de Lerna), en el que aparecerá Eyra, la Hidra, los pequeños enemigos y dos o tres tipos de arma según el tiempo que quede restante cuando se haya terminado de desarrollar lo prioritario.
