### ISSUE TITLE
Equipo Humano

### ISSUE THREAD

**Issue by AlexLabrador** [CIFP-Jose-luis-Garci/TheSingularity#19]
- [x]  Roles

- [ ] Background

**Comment by edelap00** [comment]
Álvaro Ferrándiz (Modelado y animación)
Elisa de la Peña (Arte)
Agustín Izquierdo (interfaz y UX)
Oscar García (Diseñador)
Alejandro Labrador (Programación)

**Comment by edelap00** [comment]
![fotos](https://user-images.githubusercontent.com/77675394/141266244-a5e38481-ac34-4dab-9843-2a45d6879285.PNG)
