### ISSUE TITLE
Diagrama de Gantt

### ISSUE THREAD

**Issue by edelap00** [CIFP-Jose-luis-Garci/TheSingularity#23]
Diagrama de Gant del proyecto del juego, con los hitos del calendario, entrega el lunes.
La idea es que sea visual y nos sirva realmente para gestionar cada tarea

**Comment by edelap00** [comment]
![Captura](https://user-images.githubusercontent.com/77675394/145376752-2dfc811b-9f2e-4207-9c44-555de751a073.PNG)

Tabla de aproximación de tareas que tiene el proyecto (temporal)

**Comment by agusizbus** [comment]
[gannt proyect - Hoja 1.pdf](https://github.com/CIFP-Jose-luis-Garci/TheSingularity/files/7707319/gannt.proyect.-.Hoja.1.pdf)

**Comment by agusizbus** [comment]
**Enlace a proyecto Gantt**

https://drive.google.com/file/d/1TeQL0ZV0mNqlDRG1MEW3E_Gnf7W-HZhl/view?usp=sharing
