### ISSUE TITLE
Asignar roles

### ISSUE THREAD

**Issue by AlexLabrador** [CIFP-Jose-luis-Garci/TheSingularity#4]
Álvaro Ferrándiz(Modelado y animación)
Elisa de la Peña(Arte)
Agustín Izquierdo(interfaz  y UX)
Oscar García(Diseñador)
Alejandro Labrador(Programación)

- [x]  hecho

**Comment by vcalzadaga** [comment]
No olvidéis asignar esta tarea al Millestone correspondiente (GDD)

Una vez que la tarea está en "Verify" porque ya está totalmente completada, como es el caso, tenéis que darle a CLOSE. Sólo así os dará avance
