### ISSUE TITLE
Introducción

### ISSUE THREAD

**Issue by AlexLabrador** [CIFP-Jose-luis-Garci/TheSingularity#5]
- [x] Concepto del juego
- [x] Características principales

**Comment by OscarGSanchez** [comment]
Introducción

Este es el documento de diseño de Singularity . El videojuego para PC, PlayStation, Xbox y Switch que ejemplifica todos los contenidos , información sobre desarrollo de videojuegos en 3D utilizando Unity como motor de renderizado. Este escrito tiene como objetivo principal plasmar los elementos que debe incluir Singularity y servir de carta de presentación en caso de buscar colaboradores en un futuro.

Concepto del juego
 
Singularity es un videojuego en el que controlamos a Eyra, una joven campesina que es obligada a luchar contra monstruos después de que el caos consumiera su hogar y el mundo en general. En su lucha Eyra se encontrará con dioses que le ayudarán en su incansable lucha por arreglar la línea temporal y restaurar así su mundo.

**Comment by OscarGSanchez** [comment]
Características principales:

- Un nuevo Universo mitológico a explorar: Tendremos la oportunidad de explorar un amplio territorio donde podremos descubrir un mundo totalmente nuevo, con una nueva cultura nunca antes vista.

- Un gran contenido transmedia: Singularity esta pensado desde el principio con la intención de crear un universo donde poder explorar varias plataformas y contenido audiovisual, expandiendo la historia tanto antes como después de los acontecimientos del videojuego.

- Enfocado a la comunidad de streamers y no-hitters profesionale: A la hora de crear el videojuego, pensamos en un target especifico como son los no hitter profesionales y streamers. Este tipo de juegos son perfectos para poder strimearlos, captar al mayor numero de personas, y retar a los jugadores a conseguir pasarse el juego sin daños.

- El rogue lite es un género en auge: Está más que demostrado que las mecánicas que utilizan este tipo de juegos son muy llamativas para los jugadores. Juegos como Hades, Transistor o Returnal, son juegos que han vendido muchísimo gracias tanto a su historia como a la jugabilidad.

- Apartado visual destacable. Utilizaremos un estilo Cell Shading para crear la estética de nuestro videojuego. Este estilo artístico se ha utilizado en muchas ocasiones en juegos como Zelda o Genshing Impact y con muy buenos resultados, pudiendo crear un mundo colorido y llamativo a los ojos del jugador.
