### ISSUE TITLE
Género

### ISSUE THREAD

**Issue by edelap00** [CIFP-Jose-luis-Garci/TheSingularity#6]
Género principal/ combinación de géneros

**Comment by edelap00** [comment]
Rogue lite y RPG.

**Comment by vcalzadaga** [comment]
A ver, se puede explicar mucho más. Cómo se va a implementar el género en el videojuego, qué tipo de elementos RPG se van a introducir, a qué otros títulos se parece con respecto al género... 

Os abro el asunto para que me lo completéis

**Comment by edelap00** [comment]
Rogue lite y RPG. 
La presencia de varios elementos del Roguelike, como el Hack and Slash, elementos desbloqueables y el sistema de mantenimiento de algún avance al morir , hacen de nuestro juego un Rogue-lite. 
Los elementos RPG de este juego son: el uso de distintos objetos para potenciar unas habilidades u otras, distintas armas y enemigos con características y alcance distinto, la progresión que debe seguir el usuario, la construcción de un mundo nuevo con personajes memorables y el sistema de combate flexible.
