### ISSUE TITLE
Historia y Narrativa

### ISSUE THREAD

**Issue by edelap00** [CIFP-Jose-luis-Garci/TheSingularity#8]
- [x] Lema

- [x] Historia

- [x] Plot Points

- [x] Narrativa

**Comment by OscarGSanchez** [comment]
**Lema**

¿Restablecerías la lineal temporal?

**Comment by OscarGSanchez** [comment]
**Historia**

Una invasión de monstruos asedia una aldea medieval. Eyra, una chica lista y valiente, decide enfrentarse a estos monstruos con solo una rama que ha encontrado en el suelo, pero es derrotada y termina muriendo. Momentos más tarde, Eyra revive en el interior de su hogar, pero momentos antes de la lucha donde había fallecido, solo que esta vez con un brazalete brillante en sus manos. Una voz que parece divina le dice que se lo ponga y luche. Ella sin pensárselo dos veces sale a luchar con los monstruos por segunda vez, pero esta vez un arma enorme aparece en sus manos prácticamente de la nada, como si la hubiera invocado de alguna forma.

Eyra lucha incansablemente contra las bestias hasta que las derrota. Segundos después, una figura brillante baja de los cielos y se coloca justo enfrente de Eyra. 

"Soy Väer, la diosa del tiempo. Llevamos mucho tiempo observándote Eyra y sabemos que ya estas preparada para tu destino. Una serie de eventos catastróficos ocurrirán en un futuro de forma irreversible y que implica a la destrucción de nuestro mundo   Tú, Eyra, has sido elegida para evitar esos acontecimientos y así impedir que este desastre ocurra."

En un primer momento, la protagonista reniega de su supuesto destino. Ella no tiene por que seguir unos pasos que no eligió piensa, pero un caos nunca antes visto a su al rededor le hace pensar que a lo mejor es el único modo de arreglarlo todo. Asi que sin pensarlo mucho toca la mano de Väer y todo se oscurece en una destello blanco.

Cuando Eyra consigue abrir los ojos, se encuentra en una plaza que le resulta muy familiar, pero que tiene algo muy diferente. Väer le cuenta a Eyra que los sitios que tendrá que explorar serán los mismos por los que se ha criado desde pequeña, pero en el futuro y que por eso le resulta tan familiar. Confundida, nuestra protagonista pregunta a la diosa que cual es su destino y que tiene que hacer para volver a su vida normal. 

La diosa le cuenta que su misión es avanzar por la ciudad, despejando las calles infestadas de monstruos y restaurar la lineal temporal arreglando una serie de situaciones que no deberían estar pasando. Le dice que tenga cuidado, que muchas bestias le intentaran convencer de que su destino no esta escrito y que arreglar la lineal temporal es un error. Y antes de poder decir nada, Väer se desvanece, dejando a Eyra sola en la plaza.

Eyra es obligada ahora a luchar y arreglar la lineal temporal, o eso es lo que piensa que hace al principio, ya que ira descubriendo cosas en la historia que le harán dudar de si la historia de la diosa es real y sobre todo a dudar de si es quien dice ser. La protagonista ira descubriendo poco a poco que Väer ha congelado en el tiempo a su hermano Röm, el dios del tiempo, por que éste quiere acabar con el mundo para empezar de 0, ya que el mundo que conocen terminará consumiéndose a si mismo

Gracias a los conocimientos que Eyra va consiguiendo, en la batalla final tendrá que decidir a que dios ayudar y destruir al otro para conseguir uno de los dos finales.

**Comment by OscarGSanchez** [comment]
**Narrativa**

Lo que más se ajusta a nuestra historia es una narrativa lineal, ya que literalmente el juego empieza en una época medieval y va avanzando hasta una era ciberpunk post-apocalíptica. Trabajamos con saltos en el tiempo, pero siempre de forma lineal.

**Comment by OscarGSanchez** [comment]
**Plot point**

- Inicio la historia
- 1º Encuentro con Väer
- 1º Descubrimiento de zona secreta
- 1º Boss
- -2ºBoss
- Batalla final
